export default {
  CONFIRM: 'CONFIRM',
  RESET: {
    CREATE: 'RESET_CREATE'
  },
  USER: {
    CREATE: 'USER_CREATE',
    EDIT: 'USER_EDIT',
    DESTROY: 'USER_DESTROY',
    GET: 'USER_GET',
    CONFIRM_PHONE: 'USER_CONFIRM_PHONE'
  },
  TOKEN: {
    CREATE: 'TOKEN_CREATE',
    EXTEND: 'TOKEN_EXTEND',
    DESTROY: 'TOKEN_DESTROY',
    GET: 'TOKEN_GET'
  },
  REFER: {
    REFER: 'REFER_REFER',
    USE: 'REFER_USE',
    REGISTER: 'REFER_REGISTER'
  },
  PING: 'PING',
  NOT_FOUND: 'NOT_FOUND'
}
